import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import MobileFooter from "./components/Mobile_footer";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" h-full">
      <body className=" bg-neutral-50 relative flex flex-col items-center min-h-full justify-between  ">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
