import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import MobileFooter from './components/Mobile_footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className=' relative flex flex-col items-center mx-4 mr-4 relative '>
        <Header/>

        {children}
        <MobileFooter />
      </body>
    </html>
  )
}
